apiVersion: v1
name: kibana-logstash
version: 1.0.0
description: Helm chart for Kibana and Logstash
icon: https://www.elastic.co/assets/blt282ae2420e32fc38/icon-kibana-bb.svg
maintainers:
  - name: Microsoft Social Engagement
    email: msefoundations@microsoft.com
