image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 6.2.2
  pullPolicy: Always

license:
  install: false
  image:
    repository: docker.io/mse/elasticlicense
    tag: latest
    pullPolicy: Always
  value:

es_cluster:
  name: &CLUSTER_NAME "es-cluster"
  plugins: "x-pack"
  container:
    request:
      cpu: "500m"
      mem: "1Gi"
    limit:
      cpu: "500m"
      mem: "2Gi"
  env_var:
    CLUSTER_NAME: *CLUSTER_NAME
    MINIMUM_MASTER_NODES: 2
    DISCOVERY_SERVICE: elasticsearch-discovery
    NETWORK_HOST: "0.0.0.0"
    NUMBER_OF_SHARDS: 3
    NUMBER_OF_REPLICAS: 1
    CLIENT_IGNORE_CLUSTER_NAME: false
    HTTP_ENABLE: true
    CLIENT_SNIFF: true
    HTTP_CORS_ENABLE: true
    HTTP_CORS_ALLOW_ORIGIN: "*"
    MEMORY_LOCK: false
    ES_PATH_CONF: "/usr/share/elasticsearch/config"
    MAX_LOCAL_STORAGE_NODES: 1

es_master:
  replicas:  "3"
  container:
    request:
      cpu: "500m"
      mem: "1Gi"
    limit:
      cpu: "500m"
      mem: "2Gi"
  env_var:
    ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    NODE_INGEST: false
    NODE_DATA: false
    NODE_MASTER: true

es_client:
  replicas: "3"
  container:
    request:
      cpu: "500m"
      mem: "1Gi"
    limit:
      cpu: "500m"
      mem: "2Gi"
  env_var:
    ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    NODE_INGEST: true
    NODE_DATA: false
    NODE_MASTER: false

es_data:
  replicas: "3"
  disk_capacity: "100Gi"
  storageclass: managed-premium
  container:
    request:
      cpu: "2000m"
      mem: "10Gi"
    limit:
      cpu: "2000m"
      mem: "15Gi"
  env_var:
    ES_JAVA_OPTS: "-Xms10g -Xmx10g"
    NODE_INGEST: false
    NODE_DATA: true
    NODE_MASTER: false
