{{- if .Values.watcher.install -}}
apiVersion: v1
kind: Secret
metadata:
  name: watches-secret
  annotations:
    config/checksum: {{ print .Values.watcher | sha256sum }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
stringData:
  watches.json: |
{{ include (print .Template.BasePath "/tpl/_watches.json.tpl") . | indent 4 }}
{{- end -}}
